version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3003"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wpoms
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: wpoms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
