name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Backend Image
      - name: Build Backend Docker Image
        run: |
          docker build -t backend ./backend

      # Tag Backend Image
      - name: Tag Backend Docker Image
        run: |
          docker tag backend:latest 924982554051.dkr.ecr.ap-south-1.amazonaws.com/backend-repository-alan:${{ github.sha }}

      # Push Backend Image
      - name: Push Backend Docker Image
        run: |
          docker push 924982554051.dkr.ecr.ap-south-1.amazonaws.com/backend-repository-alan:${{ github.sha }}

      # Build Frontend Image
      - name: Build Frontend Docker Image
        run: |
          docker build -t frontend ./frontend

      # Tag Frontend Image
      - name: Tag Frontend Docker Image
        run: |
          docker tag frontend:latest 924982554051.dkr.ecr.ap-south-1.amazonaws.com/frontend-repository-alan:${{ github.sha }}

      # Push Frontend Image
      - name: Push Frontend Docker Image
        run: |
          docker push 924982554051.dkr.ecr.ap-south-1.amazonaws.com/frontend-repository-alan:${{ github.sha }}